/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 10-Apr-2016 17:05:34 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `work_experiences` CASCADE
;

DROP TABLE IF EXISTS `vacancies` CASCADE
;

DROP TABLE IF EXISTS `users` CASCADE
;

DROP TABLE IF EXISTS `skills` CASCADE
;

DROP TABLE IF EXISTS `resumes` CASCADE
;

DROP TABLE IF EXISTS `messages` CASCADE
;

DROP TABLE IF EXISTS `educations` CASCADE
;

/* Create Tables */

CREATE TABLE `work_experiences`
(
	`id` INT NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`organization` VARCHAR(255) NOT NULL,
	`start_date` DATE 	 NULL,
	`end_date` DATE 	 NULL,
	`resume_id` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `vacancies`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`employer_id` INT 	 NULL,
	`contact_info` TEXT 	 NULL,
	`summary` TEXT NOT NULL,
	`description` TEXT 	 NULL,
	`salary` TEXT 	 NULL,
	CONSTRAINT `PK_vacancy` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `users`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`user_type` ENUM ('employee', 'employer', 'admin') DEFAULT 'employee' NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`encrypted_password` BLOB NOT NULL,
	`password_salt` BLOB NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`surname` VARCHAR(255) NOT NULL,
	`about` TEXT 	 NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `skills`
(
	`id` INT NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`description` TEXT 	 NULL,
	`document_id` INT 	 NULL,
	CONSTRAINT `PK_skills` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `resumes`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`employee_id` INT 	 NULL,
	`contact_info` TEXT 	 NULL,
	`summary` TEXT NOT NULL,
	`description` TEXT 	 NULL,
	`interests` TEXT 	 NULL,
	`references` TEXT 	 NULL,
	CONSTRAINT `PK_resume` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `messages`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`from` INT NOT NULL,
	`to` INT NOT NULL,
	`title` TEXT NOT NULL,
	`text` TEXT NOT NULL,
	CONSTRAINT `PK_message` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `educations`
(
	`id` INT NOT NULL,
	`university` VARCHAR(255) NOT NULL,
	`start_year` INT 	 NULL,
	`end_year` INT 	 NULL,
	`study_field` VARCHAR(255) 	 NULL,
	`description` TEXT 	 NULL,
	`resume_id` INT 	 NULL,
	CONSTRAINT `PK_educations` PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `work_experiences` 
 ADD INDEX `IXFK_work_experiences_resumes` (`resume_id` ASC)
;

ALTER TABLE `work_experiences` 
 ADD INDEX `IX_organization` (`organization` ASC)
;

ALTER TABLE `vacancies` 
 ADD INDEX `IXFK_vacancy_user` (`employer_id` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IX_surname` (`surname` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IX_user_type` (`user_type` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IX_email` (`email` ASC)
;

ALTER TABLE `skills` 
 ADD INDEX `IXFK_skills_resumes` (`id` ASC)
;

ALTER TABLE `skills` 
 ADD INDEX `IXFK_skills_resumes_02` (`document_id` ASC)
;

ALTER TABLE `skills` 
 ADD INDEX `IXFK_skills_vacancies` (`document_id` ASC)
;

ALTER TABLE `skills` 
 ADD INDEX `IXFK_skills_vacancies_02` (`document_id` ASC)
;

ALTER TABLE `skills` 
 ADD INDEX `FX_name` (`name` ASC)
;

ALTER TABLE `resumes` 
 ADD INDEX `IXFK_resume_user` (`employee_id` ASC)
;

ALTER TABLE `messages` 
 ADD INDEX `IXFK_messages_users` (`from` ASC)
;

ALTER TABLE `messages` 
 ADD INDEX `IXFK_messages_users_02` (`to` ASC)
;

ALTER TABLE `educations` 
 ADD INDEX `IXFK_educations_resumes` (`resume_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `work_experiences` 
 ADD CONSTRAINT `FK_work_experiences_resumes`
	FOREIGN KEY (`resume_id`) REFERENCES `resumes` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vacancies` 
 ADD CONSTRAINT `FK_vacancy_user`
	FOREIGN KEY (`employer_id`) REFERENCES `users` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `skills` 
 ADD CONSTRAINT `FK_skills_resumes`
	FOREIGN KEY (`document_id`) REFERENCES `resumes` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `skills` 
 ADD CONSTRAINT `FK_skills_vacancies`
	FOREIGN KEY (`document_id`) REFERENCES `vacancies` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `resumes` 
 ADD CONSTRAINT `FK_resume_user`
	FOREIGN KEY (`employee_id`) REFERENCES `users` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `messages` 
 ADD CONSTRAINT `FK_messages_users`
	FOREIGN KEY (`from`) REFERENCES `users` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `messages` 
 ADD CONSTRAINT `FK_messages_users_02`
	FOREIGN KEY (`to`) REFERENCES `users` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `educations` 
 ADD CONSTRAINT `FK_educations_resumes`
	FOREIGN KEY (`resume_id`) REFERENCES `resumes` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 ;
